services:
  hort:
    build:
      context: https://github.com/masolnada/automated-fertigation-system.git#main:web
      dockerfile: apps/dashboard/Containerfile
    container_name: hort
    restart: unless-stopped
    networks:
      - proxy_net

  hort-server:
    build:
      context: https://github.com/masolnada/automated-fertigation-system.git#main:web
      dockerfile: apps/server/Containerfile
    container_name: hort-server
    restart: unless-stopped
    environment:
      - MQTT_URL=mqtt://mosquitto:1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_PREFIX=kc868-a8
      - PORT=4000
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
